<template>
    <div class="editorial-post-page">
        <div class="editorial_bread">
            <div class="wrapper">
                <div class="editorial_bread_crumbs">
                    <router-link class="editorial" to="/editorials"></router-link> <p>Editorials</p>
                </div>
            </div>
        </div>
        <div class="editorial_post_header">
            
            <div class="editorial_head">
                <h2>AI + Law</h2>
            </div>
        </div>
        <div class="editorial_post">
            <div class="wrapper">
                <div class="editorial_post_con">
                    <div class="blog_single_banner">
                        <figure><img src="@/assets/images/blog1.png" alt=""></figure>
                    </div>
                    <div class="blog_single_container">
                        <h1>AI + Law</h1>
                    </div>
                    <div class="blog_single_body">
                        <p>        Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam reiciendis facilis molestias veniam assumenda odit iure inventore magnam placeat aspernatur id quaerat expedita, nisi et modi mollitia cupiditate sequi sed ducimus voluptate minus aperiam quis iusto! Dicta saepe enim sit commodi excepturi necessitatibus earum autem ab nulla facere, ipsam nam unde quos, aperiam tempore corrupti blanditiis eius, quo doloribus dolores ut. Quidem impedit hic ea harum officiis ipsa, atque, quasi et, cumque vitae voluptatibus perferendis iusto quibusdam pariatur eaque vero tempora. Ullam culpa enim nihil et, ut maiores sequi quasi corporis quisquam dolores veritatis quos quidem. Officia accusamus tempore aliquam reprehenderit a rerum vero ratione eius, rem itaque dignissimos excepturi ut in molestiae quas. Accusantium, nihil distinctio in alias voluptatum dolorem modi totam voluptatem sunt repellendus sapiente ut architecto, placeat molestiae doloribus fugit vitae natus fugiat eos maxime sed ex. Et voluptate aliquam, explicabo consectetur, enim sapiente eius earum velit distinctio eos laboriosam quos, vero dolorem! Alias beatae ullam, rerum ipsum sint similique repudiandae tempore tempora quod, doloremque eligendi corrupti accusamus repellat numquam necessitatibus nam itaque voluptatum dolorum nisi consequatur voluptatibus esse aliquid voluptatem? Sed eveniet maiores voluptate ipsa excepturi a, nam, consequatur nisi numquam sint tenetur repellat rerum perspiciatis dolorum quibusdam, incidunt labore error harum quia officia dignissimos. Molestiae ad minus et aliquid vitae iusto, autem saepe provident eius tenetur perferendis voluptatum quo animi sunt repellat excepturi. Expedita, molestias repudiandae atque est maxime officiis laboriosam incidunt. Quos hic dolores non at, natus, quaerat, porro voluptatem vel exercitationem doloremque cum!</p>
                        <p>        Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam reiciendis facilis molestias veniam assumenda odit iure inventore magnam placeat aspernatur id quaerat expedita, nisi et modi mollitia cupiditate sequi sed ducimus voluptate minus aperiam quis iusto! Dicta saepe enim sit commodi excepturi necessitatibus earum autem ab nulla facere, ipsam nam unde quos, aperiam tempore corrupti blanditiis eius, quo doloribus dolores ut. Quidem impedit hic ea harum officiis ipsa, atque, quasi et, cumque vitae voluptatibus perferendis iusto quibusdam pariatur eaque vero tempora. Ullam culpa enim nihil et, ut maiores sequi quasi corporis quisquam dolores veritatis quos quidem. Officia accusamus tempore aliquam reprehenderit a rerum vero ratione eius, rem itaque dignissimos excepturi ut in molestiae quas. Accusantium, nihil distinctio in alias voluptatum dolorem modi totam voluptatem sunt repellendus sapiente ut architecto, placeat molestiae doloribus fugit vitae natus fugiat eos maxime sed ex. Et voluptate aliquam, explicabo consectetur, enim sapiente eius earum velit distinctio eos laboriosam quos, vero dolorem! Alias beatae ullam, rerum ipsum sint similique repudiandae tempore tempora quod, doloremque eligendi corrupti accusamus repellat numquam necessitatibus nam itaque voluptatum dolorum nisi consequatur voluptatibus esse aliquid voluptatem? Sed eveniet maiores voluptate ipsa excepturi a, nam, consequatur nisi numquam sint tenetur repellat rerum perspiciatis dolorum quibusdam, incidunt labore error harum quia officia dignissimos. Molestiae ad minus et aliquid vitae iusto, autem saepe provident eius tenetur perferendis voluptatum quo animi sunt repellat excepturi. Expedita, molestias repudiandae atque est maxime officiis laboriosam incidunt. Quos hic dolores non at, natus, quaerat, porro voluptatem vel exercitationem doloremque cum!</p>
                        <p>        Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam reiciendis facilis molestias veniam assumenda odit iure inventore magnam placeat aspernatur id quaerat expedita, nisi et modi mollitia cupiditate sequi sed ducimus voluptate minus aperiam quis iusto! Dicta saepe enim sit commodi excepturi necessitatibus earum autem ab nulla facere, ipsam nam unde quos, aperiam tempore corrupti blanditiis eius, quo doloribus dolores ut. Quidem impedit hic ea harum officiis ipsa, atque, quasi et, cumque vitae voluptatibus perferendis iusto quibusdam pariatur eaque vero tempora. Ullam culpa enim nihil et, ut maiores sequi quasi corporis quisquam dolores veritatis quos quidem. Officia accusamus tempore aliquam reprehenderit a rerum vero ratione eius, rem itaque dignissimos excepturi ut in molestiae quas. Accusantium, nihil distinctio in alias voluptatum dolorem modi totam voluptatem sunt repellendus sapiente ut architecto, placeat molestiae doloribus fugit vitae natus fugiat eos maxime sed ex. Et voluptate aliquam, explicabo consectetur, enim sapiente eius earum velit distinctio eos laboriosam quos, vero dolorem! Alias beatae ullam, rerum ipsum sint similique repudiandae tempore tempora quod, doloremque eligendi corrupti accusamus repellat numquam necessitatibus nam itaque voluptatum dolorum nisi consequatur voluptatibus esse aliquid voluptatem? Sed eveniet maiores voluptate ipsa excepturi a, nam, consequatur nisi numquam sint tenetur repellat rerum perspiciatis dolorum quibusdam, incidunt labore error harum quia officia dignissimos. Molestiae ad minus et aliquid vitae iusto, autem saepe provident eius tenetur perferendis voluptatum quo animi sunt repellat excepturi. Expedita, molestias repudiandae atque est maxime officiis laboriosam incidunt. Quos hic dolores non at, natus, quaerat, porro voluptatem vel exercitationem doloremque cum!</p>
                        <p>        Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam reiciendis facilis molestias veniam assumenda odit iure inventore magnam placeat aspernatur id quaerat expedita, nisi et modi mollitia cupiditate sequi sed ducimus voluptate minus aperiam quis iusto! Dicta saepe enim sit commodi excepturi necessitatibus earum autem ab nulla facere, ipsam nam unde quos, aperiam tempore corrupti blanditiis eius, quo doloribus dolores ut. Quidem impedit hic ea harum officiis ipsa, atque, quasi et, cumque vitae voluptatibus perferendis iusto quibusdam pariatur eaque vero tempora. Ullam culpa enim nihil et, ut maiores sequi quasi corporis quisquam dolores veritatis quos quidem. Officia accusamus tempore aliquam reprehenderit a rerum vero ratione eius, rem itaque dignissimos excepturi ut in molestiae quas. Accusantium, nihil distinctio in alias voluptatum dolorem modi totam voluptatem sunt repellendus sapiente ut architecto, placeat molestiae doloribus fugit vitae natus fugiat eos maxime sed ex. Et voluptate aliquam, explicabo consectetur, enim sapiente eius earum velit distinctio eos laboriosam quos, vero dolorem! Alias beatae ullam, rerum ipsum sint similique repudiandae tempore tempora quod, doloremque eligendi corrupti accusamus repellat numquam necessitatibus nam itaque voluptatum dolorum nisi consequatur voluptatibus esse aliquid voluptatem? Sed eveniet maiores voluptate ipsa excepturi a, nam, consequatur nisi numquam sint tenetur repellat rerum perspiciatis dolorum quibusdam, incidunt labore error harum quia officia dignissimos. Molestiae ad minus et aliquid vitae iusto, autem saepe provident eius tenetur perferendis voluptatum quo animi sunt repellat excepturi. Expedita, molestias repudiandae atque est maxime officiis laboriosam incidunt. Quos hic dolores non at, natus, quaerat, porro voluptatem vel exercitationem doloremque cum!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>
  
<script>
export default {
    created(){ 
        this.$store.dispatch('title/setTitle', 'Read');
    },
}
</script>